### PR TITLE
Add initial pyroscope java pipeline

### PR DESCRIPTION
**Pull request by tomershafir**

### CODE REVIEW

**Comment by akvlad** [comment]
@tomershafir 
I'm currently running the collector pipeline. During the runs I encounter some exceptions.
I'll paste the messages here so they don't get lost. 
- [ ] panic: runtime error: index out of range [0] with length 0
```
panic: runtime error: index out of range [0] with length 0

goroutine 166 [running]:
go.opentelemetry.io/collector/pdata/plog.LogRecordSlice.At(...)
        /go/pkg/mod/go.opentelemetry.io/collector/pdata@v1.0.0-rcv0018/plog/generated_logrecordslice.go:56
github.com/metrico/otel-collector/exporter/clickhouseprofileexporter/ch.(*clickhouseAccessNativeColumnar).InsertBatch(0xc0021c1748?, {0xc002200018?, 0xc0000150a8?})
        /otel-collector-qryn/exporter/clickhouseprofileexporter/ch/access_native_columnar.go:71 +0xdaf
github.com/metrico/otel-collector/exporter/clickhouseprofileexporter.(*clickhouseProfileExporter).send(0xc001c7ed80, {0x7a88060, 0xc001d93490}, {0xc002200018?, 0xc0000150a8?})
        /otel-collector-qryn/exporter/clickhouseprofileexporter/exporter.go:66 +0xf1
go.opentelemetry.io/collector/exporter/exporterhelper.(*logsRequest).Export(0x7a87fb8?, {0x7a88060?, 0xc001d93490?})
        /go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.89.0/exporterhelper/logs.go:58 +0x31
go.opentelemetry.io/collector/exporter/exporterhelper.(*timeoutSender).send(0xc0021a4880?, {0x7a87fb8?, 0xc001f8aa20?}, {0x7a474f0?, 0xc002200138?})
        /go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.89.0/exporterhelper/timeout_sender.go:38 +0x98
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send(0xc000174160, {0x7a87fb8, 0xc001f8aa20}, {0x7a474f0, 0xc002200138})
        /go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.89.0/exporterhelper/retry_sender.go:128 +0x41f
go.opentelemetry.io/collector/exporter/exporterhelper.(*logsExporterWithObservability).send(0xc001c9f8c0, {0x7a88338?, 0xc00219e3b0?}, {0x7a474f0?, 0xc002200138?})
        /go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.89.0/exporterhelper/logs.go:173 +0x7e
go.opentelemetry.io/collector/exporter/exporterhelper.(*queueSender).Start.func1({{0x5ff2dc0, 0xc002200138}, {0x7a88338, 0xc00219e3b0}, 0x0})
        /go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.89.0/exporterhelper/queue_sender.go:141 +0x7a
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).Start.func1()
        /go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.89.0/exporterhelper/internal/bounded_memory_queue.go:46 +0x108
created by go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).Start in goroutine 1
        /go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.89.0/exporterhelper/internal/bounded_memory_queue.go:42 +0x55
```

- [ ] failed to insert batch: [clickhouse [AppendRow]: converting uint8 to Tuple(String, String) is unsupported]
```
2024-01-02T18:04:11.096+0200    error   clickhouseprofileexporter/exporter.go:68        failed to insert batch: [clickhouse [AppendRow]: converting uint8 to Tuple(String, String) is unsupported]      {"kind": "exporter", "data_type": "logs", "name": "clickhouseprofileexporter"}
github.com/metrico/otel-collector/exporter/clickhouseprofileexporter.(*clickhouseProfileExporter).send
        /otel-collector-qryn/exporter/clickhouseprofileexporter/exporter.go:68
go.opentelemetry.io/collector/exporter/exporterhelper.(*logsRequest).Export
        /go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.89.0/exporterhelper/logs.go:58
go.opentelemetry.io/collector/exporter/exporterhelper.(*timeoutSender).send
        /go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.89.0/exporterhelper/timeout_sender.go:38
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
        /go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.89.0/exporterhelper/retry_sender.go:128
go.opentelemetry.io/collector/exporter/exporterhelper.(*logsExporterWithObservability).send
        /go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.89.0/exporterhelper/logs.go:173
go.opentelemetry.io/collector/exporter/exporterhelper.(*queueSender).Start.func1
        /go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.89.0/exporterhelper/queue_sender.go:141
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).Start.func1
        /go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.89.0/exporterhelper/internal/bounded_memory_queue.go:46
```

**Comment by tomershafir** [comment]
@akvlad I patched a fix to receive 0 parsed profiles gracefully. Your app is probably not doing enough for async-profiler to record it. Can you try: clone pyroscope-java, tweak the "app" service in `./example/docker-compose-expt.yml` by changing a line to `- PYROSCOPE_SERVER_ADDRESS=http://host.docker.internal:8062`, run `make docker-compose-expt`

**Comment by akvlad** [comment]
@tomershafir the first error have never appeared except once. Thanks for the fix. 
The second one is reproduced every time. Please recheck.

**Comment by akvlad** [comment]
@tomershafir I don't have the ./example folder. Where is it?

**Comment by tomershafir** [comment]
@akvlad 
1. removed the dropped column profile_id from insert to fix the insert issue
2. its examples, sorry https://github.com/grafana/pyroscope-java/tree/main/examples

**Comment by akvlad** [comment]
@tomershafir great update. Everything works now.

Can you add Readme to the components you have created? Like this one https://github.com/metrico/otel-collector/blob/main/exporter/qrynexporter/README.md

**Pull request merged**
