### PR TITLE
feat: allow not have loki hint

### PR DESCRIPTION
**Pull request by Cluas**
1. Allow not have loki hint
2. Remove default label exporter OTLP

### CODE REVIEW

**Comment by Cluas** [comment]
```yaml
  config.yaml: |
    receivers:
      tcplog:
        listen_address: "0.0.0.0:54525"
      udplog:
        listen_address: "0.0.0.0:54526"
        attributes:
          collector: qryn
          loki.attribute.labels: env,app,component,cluster
          loki.format: json
```
before this PR, we need config like this when we use updlog or tcplog.

**Comment by Cluas** [comment]
My opinion is that the default is to use all attritube as labels, and if the user has set them himself, use the user settings

**Comment by Cluas** [comment]
This PR also delete default label `{expoter: OLTP}`

**Review by lmangani — APPROVED** [review]

**Review by lmangani — COMMENTED** [review]
LGTM 👍

**Pull request merged**
